### ISSUE TITLE
Timeout too short.

### ISSUE THREAD

**Issue by dreirund** [marudor/bahn.expert#618]
**Describe the bug**
I too often cannot use [marudor.de](http://marudor.de/) when I most need it: Before the data of a station or train is loaded, it errors out with timeout. It seems that the timeout comes from the JavaScript running in my webbrowser, as [dbf.finalrewind.org](http://dbf.finalrewind.org/) work fine, as well as command line perl based RIS/ IRIS request tools.

On mobile networks, slow responding internet is quite common, especially when in GPRS-only areas or high-speed bandwidth has been used up. The same holds true for the wireless internet on German trains -- where you most probably need it most when your train is delayed and you want to get ideas on how to continue your journey.

Please increase the timeout to >=300 seconds (you can add a "abort search"-button popping up after few seconds of no results).

**To Reproduce**
1. Be on a network which in general functions, but ping roundtrips is some seconds or more.
2. Open a station departure board from [marudor.de](https://marudor.de), e.g. [marudor.de/Kehl](https://marudor.de/Kehl).
3. Wait for data beeing loaded and probably observe a timeout error.

**Expected behavior**
Do not timeout after some (tens) of seconds but patiently wait for the answer(s) coming back.

**Desktop (please complete the following information):**
 - OS: *Artix GNU/Linux.*
 - Browser: *Firefox 102.0b9 (Artix).*

**Smartphone (please complete the following information):**
 - Device: *markw*
 - OS: *crDroid (Android 11).*
 - Browser *Mull (Android).*

**Additional context**
A similar web service, [dbf.finalrewind.org](http://dbf.finalrewind.org/), works well in the cases were [marudor.de](http://marudor.de/) timeouts but otherwise the network is slow but functioning.

**Comment by dreirund** [comment]
> Closed #618 as completed.

I still sometimes get timeouts (with a 25000ms message). Currently, on the train or on low quality mobile network, it is not often enough. Can you make it user-configurable or really 120 seconds at least?

Other websites which just load non-interactive HTTP stuff work well (after long waiting time).

**Comment by marudor** [comment]
Won't increase it higher. Usually a reload works way better in those network connections.
