### ISSUE TITLE
"Eisenach" don't work anymore.

### ISSUE THREAD

**Issue by MarkMcWire** [marudor/bahn.expert#626]
If I click on "Eisenach" in train run, I will redirected to "Eisenach West" and not "Eisenach".
Same for direct search in train search or usage of "UEI".

Issue is on Google Chome Version 103.0.5060.53 (Offizieller Build) (64-Bit) on OS Linux Mint 20.3 Cinnamon 5.2.7 with Kernel 5.15.0.33-generic.

**Comment by marudor** [comment]
fixed
