### ISSUE TITLE
Details-Link führt zu falschem Zug mit gleicher Zugnummer

### ISSUE THREAD

**Issue by bridgerdier** [marudor/bahn.expert#694]
In der Abfahrtstafel Bonn Hbf beim IC 5107 ([Luxemburg -] Koblenz - Düsseldorf) zeigt der Link https://bahn.expert/details/IC%205107/2022-11-04T05:13:00.000Z?evaNumberAlongRoute=8000044 auf einen IC 5107 in Belgien (Kortrijk - Brüssel - Schaarbeek), der aber mit dem für den richtigen Zug plausiblen Betreiber "DB Regio AG Mitte SÜWEX" angezeigt wird

**Comment by marudor** [comment]
Leider kein triviales Problem...
Dauert etwas
