### ISSUE TITLE
Reenable the JourneyCourse-Endpoint

### ISSUE THREAD

**Issue by linde9821** [marudor/bahn.expert#701]
**Describe the solution you'd like**
There was the following experimental endpoint `api/hafas/experimental/JourneyCourse` which I used in my application. I used it to get the course eg. the coordinates a specific journey takes. 

The Endpoint was recently removed and I didn't find another endpoint that provides the information.

**Comment by marudor** [comment]
Wont reapper.
As the URL suggested it was experimental.
I recently removed everything that was noch stable API that I do not want to maintain and deprecated stable stuff I want to remove.

Sorry, I can't maintain all the HAFAS stuff so I removed it.

**Comment by linde9821** [comment]
Alright. Still thx for your work btw and the fast response 👍 

Do you maybe know another way to get the course of a journey?
