### ISSUE TITLE
What's happening to the /api/journeys/v2/ endpoint?

### ISSUE THREAD

**Issue by theopfr** [marudor/bahn.expert#710]
**Describe the bug**
I made a simple request to the `` /api/journeys/v1/details/ICE612`` endpoint and getting the response code 401 along the the message 
>This is rate-limited upstream, please do not use it.

It worked this morning but it doesn't work now.

**To Reproduce**
1. Go to the browser
2. Simply search "https://bahn.expert/api/journeys/v1/details/ICE621"
4. See error message "This is rate-limited upstream, please do not use it."

What does that mean exactly?

**Expected behavior**
Response code 200 and the response body containing the train data. Just as the ``https://bahn.expert/api/hafas/v2/details`` endpoint.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 
 I know you are maybe working on it or making changes. Sorry for my impatience.

**Comment by marudor** [comment]
As the error suggests, The upstream API ist rate-limited and if 3rd party like you use it bahn.expert doesn't work anymore.
So please use hafas.
