### ISSUE TITLE
api documentation website returns 404

### ISSUE THREAD

**Issue by mame98** [marudor/bahn.expert#712]
**Describe the bug**
If I try to use the documentation link from the README or GitHub releases, I get a 404 page as result.

Links tested:

https://docs.bahn.expert/

https://docs.bahn.expert/#tag/Reihung/operation/Wagenreihung%20v4

**To Reproduce**

1. open one of the links above

**Screenshots**

```
404 Not Found
nginx
```

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser firefox
 - Version 108

**Comment by marudor** [comment]
This is on purpose, I no longer provide a public API.
