### ISSUE TITLE
"bahn.expert/MA" URL sometimes loads Augsburg Hbf, sometimes Mannheim Hbf

### ISSUE THREAD

**Issue by w-flo** [marudor/bahn.expert#722]
**Describe the bug**
I'm not sure if this is some recent change that was rolled out, then rolled back, then rolled out again (I'm not seeing anything in recent commits as far as I can tell).

If it's not, then there appears to be some non-determinism with the "bahn.expert/[[station ID]]" route. I have bahn.expert/ as a bookmark and just add the DS100 station code (like MA for Augsburg Hbf, MDT for Donauwörth and so on) to the URL to quickly open that station's monitor.

Sometimes, instead of Augsburg Hbf, the "MA" code opens Mannheim Hbf though. This has happened two or three times in the past two weeks or so. Probably because of the license plate code "MA" for Mannheim. That's a bit annoying, so I tried "A" as the license plate code for "Augsburg" instead. But that opens the Amsterdam station monitor, at least sometimes (I seem to remember that it successfully opened Augsburg at some point), so there is no quick way to open Augsburg.

**To Reproduce**
1. Go to https://bahn.expert/MA
2. Observe either the Augsburg or Mannheim station monitor being loaded, depending on unknown factors.

**Expected behavior**
The URL always opens Augsburg Hbf. This is what most people who use the URL directly would probably expect, as the "license plate code" to "train station" mapping is unclear and there are usually lots of train stations for each license plate district. (For the search box on the web site, having "MA" recommend Mannheim first instead of Augsburg might be more appropriate though.)

If the "Mannheim" thing is by design, I'd expect "bahn.expert/A" to open Augsburg instead of Amsterdam, as this appears to be mostly a Germany-centric web site.

Or maybe an additional route "bahn.expert/ds100/MA" could be introduced to make the meaning of that parameter explicit, unless that already exists.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.10
 - Browser: Firefox
 - Version: 108.0.1

**Additional context**
I believe this happened on my Android smartphone using Firefox, too. I don't think it matters as it appears to be a server-side issue.

**Comment by w-flo** [comment]
Thanks for the quick reply and explanation!

If this happens a lot, I guess one way to possibly fix it is by adding a custom DS100 => station name mapping to the code (like "MA" => "Augsburg Hbf"). Then for every request, if the degraded API has to be used, check if the URL param matches a key in that map. If there is a match, call the degraded API to search for the the map value (full station name) instead of the URL param.

It would be rather tedious work for little gain though, and I'm not sure if the DS100 data including "good" full station names is available under an open license.

**Comment by marudor** [comment]
I deployed something yesterday that should fix this in most cases.  
So even the degraded api should handle rl100.
