### ISSUE TITLE
Public API?

### ISSUE THREAD

**Issue by derwaldgeist** [marudor/bahn.expert#723]
Hi Marudor, suddenly, our great integration with your public API stopped working. I tried to find the original repo, but only found this one stating that the public API is gone. This is very sad. What's the reason for this? And is there any chance that can we do to get an API back, even if this means to host it ourselves? Or is there now an alternative OpenData service by DB we could use instead?

**Comment by marudor** [comment]
You need to find the secrets & use the undocumented apis yourself now.
bahn.expert doesnt support api usage anymore.

**Comment by derwaldgeist** [comment]
Ok, so you mean to implement something like bahn.expert myself? That's a pity. What's the reason for taking this down? It was a super awesome service.
