### ISSUE TITLE
Falsche Detailsansicht

### ISSUE THREAD

**Issue by DerChaot** [marudor/bahn.expert#726]
**Describe the bug**
IC 60470 wir unter Zugsuche als Bus in Dresden angezeigt.

**Comment by marudor** [comment]
Funktioniert einwandfrei, nicht nachvollziehbar.

**Comment by DerChaot** [comment]
Interessant, das ging vorhin zumindest nicht. Von Göttingen nach Hannover morgen um 4:39 wird zumindest beim klick auf Details als dieser Bus angezeigt.
![Uploading 817F7AD5-B850-445B-9B48-9904D64BACFA.png…]()

**Comment by DerChaot** [comment]
Ich war der Meinung, dass die Zugsuche vorhin den gleichen Fehler hatte, deswegen habe ich es so unspezifisch geschrieben. War vielleicht aber auch eine Verwechslung des Tabs

**Comment by marudor** [comment]
Sollte jetzt tun.
