### ISSUE TITLE
Verspätungs/Ausfallstatistik für einzelne Züge

### ISSUE THREAD

**Issue by efpage** [marudor/bahn.expert#728]
Hallo Thies,

vielen Dank für Deine tolle Bahn-Seite. Sehr hilfreich und teilweise auch erschreckend zu sehen, wie viele Züge ausfallen.

Mir ist nur aufgefallen, dass die Bahn Verspätungsdaten sehr schnell wieder löscht. Gestern hatte der ICE11 z.B. 57 Minuten Verspätung, heute steht da aber nichts mehr in den Bahndaten. Ich würde mir daher also gerne eine Seite bauen, die die Züge jeweils während der Reisedauer abfragt und die Daten als Statistik speichert um mal eine Übersicht zu bekommen. Vollkommen unverschämt ist die Seite https://www.zugfinder.net/de/zug-ICE_11, danach wäre der Zug gestern pünktlich gewesen, da findet man nur vollkommende Phantasiewerte.

Sowas kann man natürlich nicht allgemein machen, für mich persönlich reichen da auch einzelne Verbindungen, die ich öfter fahre. Aber vielleicht könnte ich die Verspätungs/Ausfall-Informationen zu einem Zug direkt von Deiner Seite als JSON lesen, wenn es dafür ein Feature gibt? 

Vielen Dank jedenfalls für Dein Engagement und deine tolle Seite

**Comment by marudor** [comment]
Direkt per json, nein.
Die Zugsuche funktioniert auch in der Vergangenheit.
