### ISSUE TITLE
API: Alle Züge in Zeitraum

### ISSUE THREAD

**Issue by YvesRoyale** [marudor/bahn.expert#738]
**Is your feature request related to a problem? Please describe.**
Ich würde gerne nach eigenen Regeln Routings suchen. Am geeignete erscheint mir dafür ein eigener Suchalgorithmus basierend auf einem eigenen Graphen mit allen in Frage kommenden Zügen. Dazu brauche ich eine Liste aller Züge inkl. Zwischenhalte Plan/Ist-Zeiten.

**Describe the solution you'd like**
Eine Möglichkeit, mit einem API-Aufruf eine Liste aller Züge in einem bestimmten Zeitraum aufzurufen, ggf. mit geografischer Einschränkung

**Describe alternatives you've considered**
Sehr viele Abfragen der Abfahrtstafeln verschiedener, heuristisch ermittelter, möglichst zentraler Bahnhöfe.

**Additional context**
Ich bin auch offen für Hinweise zu sonstigen APIs, die mir diese Info liefern könnten, finde aber leider nichts. Alle APIs scheinen nur Abfragen zu bestimmten Zügen oder zu bestimmten Bahnhöfen zu ermöglichen.

**Comment by marudor** [comment]
Gibts nicht.
