### ISSUE TITLE
Absturz Abfahrtstafel von Nürnberg Hbf

### ISSUE THREAD

**Issue by Kilian239** [marudor/bahn.expert#746]
**Describe the bug**
Beim Aufrufen der Abfahrtstafel von Nürnberg Hbf bricht die Anwendung mit einem "unbekanntem Fehler" ab.

**To Reproduce**
Eingabe ins Suchfeld, Aufruf über Favoriten oder beim Klick auf "Nürnberg Hbf" in einem Zuglauf

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera
 

**Smartphone (please complete the following information):**
 - OS: Android 9
 - Browser : Samsung Internet

**Comment by marudor** [comment]
Ups...
Da hat mein fix wohl etwas vergessen.
