### ISSUE TITLE
Falsche Ankunftszeit in Detail-Ansicht

### ISSUE THREAD

**Issue by amrollbia** [marudor/bahn.expert#747]
**Describe the bug**
In der Detail-Ansicht kommt es vor, dass bei einer verfühten Ankunft eines Zuges an einem Halt (als bestätigte Meldung), diese verfühte Ankunftszeit auch als Plan-Ankunftszeit gezeigt wird. In der Abfahrten-Ansicht wiederum wird die verfrühte Ankunft nicht gezeigt, dafür aber die korrekte planmäßige Ankunftszeit.

**To Reproduce**
Ein Beispiel ist der Zuglauf des EC 174 vom 21.02.2023

**Expected behavior**
Die planmäßige Ankunftszeit soll sich durch die tatsächliche Ankunftszeit nicht ändern. Die angezeigte reale Ankunftszeit in der Abfahrten-Ansicht soll der tatsächlichen Ankunftszeit entsprechen.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1376257/220332967-1066238d-4902-4c3f-bac6-313154d1f889.png)
Falsche planmäßige Ankunftszeit in der Detail-Ansicht
![grafik](https://user-images.githubusercontent.com/1376257/220333145-baea8daf-60bd-4a02-ae2e-672a951397e0.png)
Richtige planmäßige Ankunftszeit in der Abfahrten-Ansicht, allerdings falsche tatsächliche Ankunftszeit.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 110.0

**Smartphone (please complete the following information):**
 - Device: Xioami 11T
 - OS: MIUI Global 13.0.9 (Android 12)
 - Browser: Firefox
 - Version: 111.0b3

**Additional context**
Das Problem scheint nicht bei verfrühten Ankunftszeiten aufzutreten, die nur prognostiziert sind.

**Comment by marudor** [comment]
Andere Datenquellen, ist kein Darstellungsproblem.
