### ISSUE TITLE
Filteroptionen bei Routensuche

### ISSUE THREAD

**Issue by Jannik-Schrempp** [marudor/bahn.expert#750]
Ich fahre gerne mit den neuen IC 2 Zügen (Stadler Kiss). Es wäre schön, wenn man bei der Suche für die Route nach dieser Baureihe filtern könnte.

Das Tool ist richtig cool. Vielen Dank dafür!
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by marudor** [comment]
Da ich hier durch upstream limitiert bin, nicht möglich.
