### ISSUE TITLE
Cookies Not Stored Permanently

### ISSUE THREAD

**Issue by bama35453** [marudor/bahn.expert#753]
**Describe the bug**
If the user saves personal favorites or defines settings which pieces of information to show or not to show these get lost after a few days.
Apparently the cookies are saved for a few days only. When using the page regularly this is very annoying since the settings have to be defined over and over again.

**To Reproduce**
See description

**Expected behavior**
Store the respective cookies for as long as technically possible

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome, Brave
 - Version all versions

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S22 Ultra, Samsung Galaxy Tab S7
 - OS: Android 13
 - Browser Chrome, Brave
 - Version all versions

**Additional context**

**Comment by marudor** [comment]
Thats your browser. They already get stored as long as possible.
