### ISSUE TITLE
"Zeige Zeiten mit Verspätung" versteckt Planabfahrt

### ISSUE THREAD

**Issue by bridgerdier** [marudor/bahn.expert#754]
**Describe the bug**
Default werden nun Plan-Abfahrt + Prognose-Abfahrt gezeigt. Der Switch "Zeige Zeiten mit Verspätung" ändert das auf Prognose-Abfahrt + Verspätung (linksbündig, aber das ist ein anderes Thema)

**Expected behavior**
Entweder dieser Switch oder eine alternative Option sollte das alte Anzeigeverhalten "Plan-Abfahrt + Verspätung"

**Additional context**
Die Planabfahrt ist ein wichtiges Orientierungsmerkmal zur Identifizierung eines Zuges und wird z.B. auf den Anzeigern am Bahnsteig prominenter als die Zugnummer angezeigt. Deshalb ist sie gerade für den flüchtigen Blick unverzichtbar.

**Comment by marudor** [comment]
Nein. Gibt den neuen default und über die option den alten default. Rest wirds nicht geben.
