### ISSUE TITLE
Allow to pass settings in the URL.

### ISSUE THREAD

**Issue by dreirund** [marudor/bahn.expert#760]
**Is your feature request related to a problem? Please describe.**

When I create search shortcuts or bookmarks to specific [bahn.expert](http://bahn.expert/)-screens, all my settings are usually lost if I don't kep cookies or if I just happen to use another browser.

**Describe the solution you'd like**
The ability to pass settings in the URL, as with [dbf.finalrewind.org](http://dbf.finalrewind.org/).  
*(For example, an URL there could look like `https://dbf.finalrewind.org/magdeburg+hbf?detailed=1&past=1&rt=1`.)*  
Or, if this feature is already there, provide a "*permalink*"-knob on the website.

**Comment by marudor** [comment]
you can. Name them just like the cookie, it will override the default setting (but not persist into a cookie, only for this session.)

**Comment by radasbona** [comment]
@marudor hi, i has the same request. But i have no idea what you mean with name it like the cookie.
Can you post an example url? I'm looking for an directlink for Nürnberg with just to show RE and RB trains. (or just plattform 12-23)

**Comment by radasbona** [comment]
Thanks a lot.
I was a great help.
