### ISSUE TITLE
Times are shown in UTC on Android with Firefox browsers.

### ISSUE THREAD

**Issue by dreirund** [marudor/bahn.expert#761]
### Describe the bug

With some browsers/ systems, the times are given in UTC rather than in local (German) railway time, which is, depending on summer time, 1 or 2 hours earlier than local time. With other browsers on the same operating system, the times are given in local time.

The clock of the operating system's user interface does show local time. The timezone of the operating system is "Europe/Berlin".

I have this on Android with the following browsers:

* "[Mull](https://f-droid.org/en/packages/us.spotco.fennec_dos)" android browser (Firefox variant),
* [Tor Browser](https://guardianproject.info/apps/org.torproject.torbrowser/) (Firefox variant).

I do not have this on Android with the following browsers:

* "[Mulch](https://gitlab.com/divested-mobile/mulch)" (chromium-based),
* builtin chromium,
* "[EinkBro](https://f-droid.org/en/packages/info.plateaukao.einkbro)" ("[FOSS-Browser](https://github.com/scoute-dich/browser)"-based).

I also do not have it on Artix GNU/Linux with Firefox.

### To Reproduce

Steps to reproduce the behaviour:  
1. Use on of the mentioned browsers on my Android operating system,
2. 
   a) Go to any train time information at [bahn.expert](http://bahn.expert/), e.g. [bahn.expert/München Hbf](http://bahn.expert/M%C3%BCnchen+Hbf),
   b) Oben the same URL with the "Mull"-Browser, or on my laptop; or a similar view at [dbf.finalrewind.org](http://dbf.finalrewind.org), e.g. [dbf.finalrewind.org/München Hbf](http://dbf.finalrewind.org/M%C3%BCnchen+Hbf), or look at the physical departure board at the corresponding station,
3. see that 2.a) is one or two hours earlier than 2.b).

### Expected behavior

See times in local time, which is the convention all over Europe for any public transport timetable information.

If other timezone display is intendet, provide a configuration option to switch between local railway time (default), UTC, and local device time.

#### Desktop (please complete the following information):
 - OS: [Artix GNU/Linux](http://artixlinux.org/)
   - Version: Rolling release
 - Browser: Firefox (developer edition)
   - Version 112.0b6

#### Smartphone (please complete the following information):
 - Device: markw
 - OS: [crDroid](http://artixlinux.org/)
   - version: 7.6 (Android 11)
 - Browser 1: Mull (Firefox based)
   - Version: 111.1.0
 - Browser 2: Tor Browser (Firefox based)
   - Version: 102.2.1

**Comment by marudor** [comment]
Times are Client specific. You have a UTC client in that case. Not a bug.
And no, Won't provide a setting.

**Comment by dreirund** [comment]
> Times are Client specific. You have a UTC client in that case. Not a
> bug. And no, Won't provide a setting.

OK, I found out that when I configure firefox to "resist
fingerprinting", it also reports itself as UTC. :-(.

Bad client.
