### ISSUE TITLE
No train names anymore

### ISSUE THREAD

**Issue by sandrosg1** [marudor/bahn.expert#764]
**Describe the bug**
The "Taufname" of long distance trains ICE are no longer shown. Instead just a number is displayed.

**To Reproduce**
1. Go to https://bahn.expert/Frankfurt(Main)Hbf
2. Define the filter just for long distance trains such as ICE 
3. Click on any train line in the overview
4. All train related settings are active such as "Fahrzeuggruppenname" und "UIC" No. 

**Expected behavior**
Usually the train name was shown below the coach sequence

**Screenshots**
<img width="1312" alt="Screenshot 2023-04-02 at 06 38 05" src="https://user-images.githubusercontent.com/66001535/229331707-f44adb1a-02a8-4873-9d4c-7d28e9b54163.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.7 Catalina
 - Browser MS Edge Version 111.0.1661.62 (Official build) (x86_64)

**Additional context**
I tried it with several browsers such as Edge Safari and Chrome. Seems to be a backend system issue.

Many thanks for checking on this 
Sandro

**Comment by marudor** [comment]
Not a bug. No upstream real live data available. Hence the "Plandaten"
For those I don't know the exact vehicle and can't tell you the name

**Comment by sandrosg1** [comment]
Ok, understand. So any idea if those upstream data will become available once again ? Thx
