### ISSUE TITLE
Der Wagenplan für den IC Kiss ist falsch. Die Sitzplätze und die Aufteilung der Tische und Sitze ist nicht richtig.

### ISSUE THREAD

**Issue by Bummelbahner** [marudor/bahn.expert#765]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marudor** [comment]
Ich gebe die offizielle Info raus aktuell. (Das PDF) kann ich nix für.
