### ISSUE TITLE
Show reservation options and free seats

### ISSUE THREAD

**Issue by oleschum** [marudor/bahn.expert#771]
**Is your feature request related to a problem? Please describe.**
Traveling with a small child is challenging. It is nice to use the "Kleinkindabteil" as it gives much more space and comfort. However, it is not possible to search for only those connections in which the "Kleinkindabteil" is free. With "Kleinkindabteil" I really mean the separate compartment in an ICE, not the general family area.
It would be nice to use this as a filter criterion.

**Describe the solution you'd like**
The ideal solution would be that one can filter the connections not only by number of changes and time for changes, regional trains etc., but also include a filter for the reservation options. Others might be interested in e.g. only those connections in which there is a window seat in the quiet area.

**Describe alternatives you've considered**
I have a built my own solution using selenium for webscraping: https://github.com/oleschum/dbressuche It is a standalone python tool that searches for connections based on the reservation options. This, however, is not really fast since it uses webbrowser automation. Direct API access would be much nicer. However, I did not find a way to do it this way.

**Comment by marudor** [comment]
Out of scope unless API exists.
