### ISSUE TITLE
Mit der Bitte um Aufnahme von weiteren Schweizer Bahnhöfen.

### ISSUE THREAD

**Issue by JO70** [marudor/bahn.expert#785]
**Describe the solution you'd like**
Bahnhof Solothurn 
Bahnhof Kreuzlingen 
Bahnhof Mannenbach-Salenstein 
Vielen Dank für die App!
J. Manns 

**Describe alternatives you've considered**

**Additional context**
.

**Comment by marudor** [comment]
Im Routing gehen davon welche. Für die Abfahrten aktuell nicht möglich. Die Quelle die ich nutze ist von der Deutsche Bahn und ich hab keine Zeit da eine Seperate für die SBB zu pflegen.
Entweder ich bekomme Quellen von der DB die das auch können oder es wird nicht passieren.
