### ISSUE TITLE
Berlin Treptower Park wird nicht angezeigt

### ISSUE THREAD

**Issue by tciberlin** [marudor/bahn.expert#788]
Hi, seit kurzem kann der Bahnhof Berlin Treptower Park nicht mehr angezeigt werden. (Siehe Screenshots)

![image](https://github.com/marudor/bahn.expert/assets/3908961/ac2d5a56-5d19-4e3d-8d53-49b09a3b4d7c)

![image](https://github.com/marudor/bahn.expert/assets/3908961/f5ea15cc-7b04-4c8f-a5bc-98acbb14c7eb)

**Comment by marudor** [comment]
Upstream Problem. Wird bestimmt bald behoben. Kann ich nichts tun.
