### ISSUE TITLE
Zugsuche lässt für Zugnummer nur Zahlen  zu

### ISSUE THREAD

**Issue by hanna-becker** [marudor/bahn.expert#798]
**Describe the bug**
Auf meinem Smartphone (Android, Galaxy S23) öffnet sich nur die Zahlentastatur für das Zugnummer Input-Feld. Meine "Zugnummer" heißt aber "Bus EV". Von einem anderen Dokument kopieren und einfügen funktioniert als Workaround leider auch nicht, es wird seltsamerweise nur ein "e" gepastet.

**To Reproduce**
1. Go to 'Zugsuche' on an Android device
2. Click on 'Zugnummer'
3. Try entering letters
4. See that it doesn't work

**Expected behavior**
Eingabe von Buchstaben als Zugnummer ist möglich.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S23 
 - OS: Android 13
 - Browser Chrome 
 - Version 116.0.5845.163

**Comment by marudor** [comment]
Nein, dein Bus hat trotzdem eine Nummer, die wird dir nur nicht gesagt.
Ist also kein Bug.

**Comment by hanna-becker** [comment]
![Screenshot_20230901_120538_DB Navigator](https://github.com/marudor/bahn.expert/assets/27636497/618a9add-0f72-4b40-bfbb-fbf7a793e643)

Wie finde ich solche Fahrten dann in der Suche?

**Comment by marudor** [comment]
Über offizielle Wege garnicht.
https://bahn.expert/routing
