### ISSUE TITLE
travelsWith is buggy

### ISSUE THREAD

**Issue by Ein-Tim** [marudor/bahn.expert#799]
**Describe the bug**
The travelsWith feature can sometimes show the same "Vereinigung" two times, as you can see in this screenshot:

<img src="https://github.com/marudor/bahn.expert/assets/67682506/b81d9ed9-ed3a-4737-9f2e-6c0b92c84b21" width="300">

**To Reproduce**
Not entirely sure as this does not happen every time.

**Expected behavior**
No duplicates.

**Screenshots**
See above.

**Smartphone:**
 - Device: iPhone 14 Pro
 - OS: iOS 16.6
 - Browser Safari

**Additional context**
Maybe this is not a problem with bahn.expert but the Bahn backend?

**Comment by marudor** [comment]
Technically a Problem with the upstream API.
I can most likely filter duplicates though

**Comment by Ein-Tim** [comment]
That would be a nice-to-have!

**Comment by marudor** [comment]
Should be fixed by now (By me filtering duplicates)
