### ISSUE TITLE
UEX / Fernverkehr

### ISSUE THREAD

**Issue by GeorgeHamp** [marudor/bahn.expert#801]
**Describe the bug**
Zugsuche findet bei Einstellung "nur Fernverkehr" scheinbar keine UEX?

**To Reproduce**
"Zugsuche"
"Nur Fernverkehr, nur aktuelle Züge"

Die Eingabe von 329 findet den UEX 329 nicht. Vermutlich ist diese Zuggattung nicht als "Fernverkehr" hinterlegt.
339 wird hingegen gefunden, springt in der Anzeige von DPF auf UEX

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- Windows
- Chrome 117

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marudor** [comment]
Kein Bug. Datenquelle sagt ist kein Fernverkehr.
