### ISSUE TITLE
Add option to hide pin icons on the map view

### ISSUE THREAD

**Issue by dancojocaru2000** [marudor/bahn.expert#802]
**Is your feature request related to a problem? Please describe.**
The pin icons are quite big and often hide parts of the map.

**Describe the solution you'd like**
It would be great if there would be an option to either hide the pins, or replace them with small dots that don't cover big parts of the map.

**Additional context**
Consider the following screenshots comparing bahn.expert and Apple Maps showing S 19 from Aachen Hbf to Hennef (Sieg):

![Screenshot of bahn.expert showing the map of S 19 (31004) from Aachen Hbf to Hennef (Sieg)](https://github.com/marudor/bahn.expert/assets/9626761/5070d257-bbb4-41f4-9256-43e9ee181b9f)

<img width="1463" alt="Screenshot of Apple Maps on macOS showing the route of S 19 from Aachen Hbf to Hennef (Sieg)" src="https://github.com/marudor/bahn.expert/assets/9626761/a7b250da-3cf9-4c83-a22a-7bdbf6a8cd4f">

**Comment by marudor** [comment]
Fixed by #803
