### ISSUE TITLE
Missing pop up for special seat indicators on BR 411 1st/2nd series

### ISSUE THREAD

**Issue by sysvinit** [marudor/bahn.expert#811]
**Describe the bug**

The pop-up for showing seat number ranges for special seating (e.g. disabled seating or BahnBonus seats) on BR 411 trains explicitly tagged as the 1st or 2nd series is missing from the train formation display in the train itinerary view.

**To Reproduce**

Navigate to a train itinerary operating a BR 411 trainset which is explicitly reported to be using a 1st or 2nd series train, and click on any station to expand the train formation view. A red dot is shown on carriages 27/37 and 28/38 to indicate that these carriages contain BahnBonus seats, and likewise an icon on carriage 22/32 to indicate that this carriage has disabled seating. However, there is no "Plätze" link below these carriages to trigger the pop-up which displays the seat number ranges for special seats.

**Expected behavior**

There should be a "Plätze" link below the carriages with special seats on these BR 411 trains, which triggers the pop-up with the seat ranges, as with other IC and ICE Baureihen.

**Screenshots**

The screenshot below shows ICE 92 and ICE 1092 for comparison, which run coupled between Nürnberg and Berlin. ICE 92 is a 2nd series BR 411, which exhibits the behaviour described above, whereas ICE 1092 is a BR 415, which has the UI controls to trigger the pop-up as normal.

![Screenshot 2023-11-05 at 15-31-06 ICE 92 @ 05 11 2023](https://github.com/marudor/bahn.expert/assets/33266253/7a07e00b-a2ca-43ad-b235-3c2c6969be21)

**Desktop**
 - OS: macOS 14.1 Sonoma
 - Browser: Firefox
 - Version: 119

**Additional context**

This looks like missing cases in the special seats handling code. The code here only tests for a Baureihe identifier string of "411", however the code differentiates between the 1st and 2nd series BR 411 trainsets ("411.S1" and "411.S2") elsewhere. For example, the the relevant excerpt from the function for BahnBonus seats:

https://github.com/marudor/bahn.expert/blob/d72c167ea51c8f27f0ba5f38e531a5e9237347c5/src/server/coachSequence/specialSeats.ts#L35-L43

**Comment by marudor** [comment]
fixed by 55b69db89f49b59edd0416a78e4d13970912138c
