### ISSUE TITLE
Routing Verbindung nur für nächsten Tag sichtbar

### ISSUE THREAD

**Issue by caradas** [marudor/bahn.expert#821]
**Describe the bug**
Routing wird kurz vor Abfahrt nicht mehr gefunden

**To Reproduce**
1. Go to 'Routing'
2. Select Bamberg as Start
3. Select Dortmund Hbf as Destination
4. Select "nur Nahverkehr"
5. Set Time to 15:00
6. Dont find connection

**Expected behavior**
Die verbindung die bahn.de vorschlägt in der Liste, Fahrtzeit 6h 33min

**Screenshots**
![grafik](https://github.com/marudor/bahn.expert/assets/3154252/f939644e-4e65-4fae-96e8-8324708bc33e)
![grafik](https://github.com/marudor/bahn.expert/assets/3154252/e447cd73-88f1-4964-b722-ff48149288fe)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox

**Additional context**
Einige Tage im voraus wird die Verbindung noch angezeigt und am Abfahrtstag verschwindet diese. Jeweils Abfahrtszeit 15:26
Der Umstieg in Hanau nach Friedberg geht verloren.

**Comment by marudor** [comment]
Sollte inzwischen gehen
