### ISSUE TITLE
Zugname wird nicht angezeigt

### ISSUE THREAD

**Issue by ComputerGod63** [marudor/bahn.expert#825]
Hallo,

wenn man z.B. beim ICE 29 nachschaut steht der Zugname (z.B. Dortmund ) nicht da.
Wäre schön wenn es behoben sein würde.
Zugname steht
![Screenshot 2024-01-13 083158](https://github.com/marudor/bahn.expert/assets/89375593/d7e05c1a-89b0-4265-a4a0-802430180290)
Zugname steht nicht
![Screenshot 2024-01-13 083014](https://github.com/marudor/bahn.expert/assets/89375593/828c0326-454c-4769-9488-80b130f03010)

**Comment by marudor** [comment]
Steht dran wenn die Quelle es kennt (über den genauen TZ)
In dem Fall war der nicht bekannt => kann den Zugnamen nicht setzen.
Das hat nichts mit der Fahrtnummer zu tun.
