### ISSUE TITLE
Abfahrten: Zeitfilter hinzufügen

### ISSUE THREAD

**Issue by muescha** [marudor/bahn.expert#845]
**Is your feature request related to a problem? Please describe.**

Ich schaue mir die Abfahrten an einem Bahnhof an. Möglicherweise sitze ich schon im Zug, und möchte meinen aktuellen Zug suchen. Da jedoch nur die zukünftigen Züge angezeigt werden sehe ich nun meinen aktuellen Zug nicht.

**Describe the solution you'd like**

Eine Zeitauswahl hinzufügen, dass ich -15min oder eine beliebige Zeit aufrufen kann

**Describe alternatives you've considered**
Ich habe schaut ob es im Einstellungen Menü rechts oben eine Option dafür gibt die Zeit einzustellen.

**Additional context**

**Comment by marudor** [comment]
gibt es nennt sich lookbehind als einstellung oder query parameter.
