### ISSUE TITLE
Echtzeitdaten Nahverkehr 

### ISSUE THREAD

**Issue by DrSchallmeister** [marudor/bahn.expert#848]
Lieber Marudor,

erstmal danke für deine tolle Arbeit mit dem BahnExperten, die auch mir das Reisen erleichtert :-)

Mir ist aufgefallen, dass unser lokaler Nahverkehrsanbieter Echtzeitdaten zu Bus & Tram hat, diese aber nicht bei dir im BahnExperten auftauchen.

Ganz konkret geht es um die Stadtwerke Augsburg in Bayern ("swa") und die lokalen Augsburger Verbindungen. 

In der swa Mobil App sowie beim "Bayern-Fahrplan" (App "MoBY") gibt es diese Echtzeitdaten problemlos.

Meine Anfrage wäre daher, ob du diese Echtzeitdaten auch im BahnExperten mit einbinden könntest.

Vielen Dank schonmal und bei Fragen gerne melden ...

VG

**Comment by Ein-Tim** [comment]
Hast du mal geschaut ob die Echtzeitdaten auch im DB Navigator (bzw. DB Business Navigator) auftauchen. Falls nein, sendet die swa diese Daten nicht an die entsprechenden APIs der Bahn.

**Comment by marudor** [comment]
Aktuell nutz ich nur RIS APIs (RIS::Journey für Fahrten) oder HAFAS (DB Business Navigator)
Ich arbeite dran den aktuellen Navigator anzubinden. Dort finden sich z.B. Auslastungen die nur dort zu finden sind.
Es ist definitiv out of scope wenn ich auch noch für Regionale Dinge eigene Datenlieferanten anbinden muss.
So lange sie also nicht im Navigator/bahn.de sind kann ich das leider nicht erfüllen.

**Comment by DrSchallmeister** [comment]
Danke für die schnelle Antwort 👍 

Weißt du zufällig, an wen man sich da bei der Bahn wenden kann, damit die das evtl. in deren Systeme bringen?

**Comment by marudor** [comment]
Da ich konkret mit den Stellen arbeiten: Bei der Bahn freuen wir uns über bessere Daten (Reisendeninformation, TR/SR)
Ich vermute die Stadtwerke Augsburg müssen da mehr liefern.
Falls du da insider informationen hast kannst du dich gerne melden. Sonst müssen wir wohl leider einfach warten. Du kannst dich im Zweifel natürllich beim Lokalen Verbund beschweren das die Echtzeit Informationen nicht im DB Navigator sind.
In dem Fall das sie dort sind dürften sie auch bei mir auftauchen.

**Comment by DrSchallmeister** [comment]
Nach diversen Telefonaten: Der Fehler scheint wohl bei der DB IT zu liegen. SWA/AVV Augsburg füttern DEFAS wohl korrekt. Es liegt jetzt ein Ticket bei der DB IT, mal schauen, was passiert. Danke für eure Unterstützung 👍
