### ISSUE TITLE
Time zone

### ISSUE THREAD

**Issue by anr-ableton** [marudor/bahn.expert#849]
This is a minor change request. The time zone adjusts to the zone of the phone. I look from UK and see the departure as 1:25pm, but now I am in Brussels, I see 2:25pm. This is preferred. I want to see the time locally. 

Congratulations on such a great site! Many times I've used on these long trips 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by marudor** [comment]
Didnt see any request or issue in your message.
Current behavious is to always match the time of your device. This is intended and works.

**Comment by anr-ableton** [comment]
ah, okay, so if I'm in England, I would see the time as it is here, not as it is at a station in say, Belgium. It's probably not often this occurs.

**Comment by anr-ableton** [comment]
The request would be: Match the time of departure in the time zone of the station.

**Comment by marudor** [comment]
Wont do. Time will be based on your device.
