### ISSUE TITLE
Time zones impact departure times 

### ISSUE THREAD

**Issue by Luuuuuis** [marudor/bahn.expert#850]
**Describe the bug**
I currently have my mobile phone set to GMT+8, which is why the departure times of German trains are also changed. (Depends on summer or winter time and how much). However, this makes no sense, as the departure times of German trains in Germany do not change regardless of which time zone you are in. This can be very confusing if you fly to Germany and think the train will leave at the time shown, but in fact it leaves 7 hours earlier. 

**To Reproduce**
1. Change your devices time zone
2. Look at the departure times of trains
3. See that they are different

**Expected behavior**
The date and time of the train should be displayed in the time zone where the train itself is. Maybe show the time zone if it differs from the device.

**Screenshots**
![IMG_3976](https://github.com/marudor/bahn.expert/assets/45736619/a77b91de-d4b0-4315-a70c-0c2e2129339f)
![IMG_3975](https://github.com/marudor/bahn.expert/assets/45736619/668cd09b-2cfd-4d90-bf2b-e87488eff5bf)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome 
 - Version: 122

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: 17.3.1
 - Browser: Chrome
 - Version: 122

**Comment by marudor** [comment]
this is on purpose. You told your phone you want times in a Singapure time. And thats what I show.

**Comment by Ein-Tim** [comment]
FYI: This issue is more or less a duplicate of #849.
