### ISSUE TITLE
Train search results for 76539 are off by one in date, stay at the same date when trying to go down from 2024-04-03 to 2024-04-02, and infinite load when trying to go down one more day.

### ISSUE THREAD

**Issue by dreirund** [marudor/bahn.expert#857]
### Describe the bug

Train search results for 76539 are off by one in date, stay at the same date when trying to go down from 2024-04-03 to 2024-04-02, and infinite load when trying to go down one more day.

### To Reproduce

1. Open [local train "76539" for 2024-04-03](https://bahn.expert/details/DPN%2076539/2024-04-03T11:32:43.000Z/?profile=db&station=8010026):  
   ![trainsearch_76539](https://github.com/marudor/bahn.expert/assets/1590519/2eeb6e4e-cb89-49a0-b499-a55857faed1c),
2. See the result for 2024-04-04:
   ![trainsearch-result_76539](https://github.com/marudor/bahn.expert/assets/1590519/111f00a3-df59-4ef7-b418-02dd07dd7073),
3. Click back two days,
4. See that on the second click, the date shown does not count down anymore (it is still at 2024-04-03)
5. Click back one day more,
6. See that the page stays busy in "loading" but does not load anything:  
   ![infitite-load](https://github.com/marudor/bahn.expert/assets/1590519/4c77b678-f72e-4081-9744-a55f8ebb4515),
7. Click back one more day and see the result for 2024-04-01,
8. Click forward one day and see the result for 2024-04-03,
9. Click forward two more days, and then back one day, and again see infinite loading
   *(actually, infinite load then can be reproduced regularly when going forward and then going backward).*

### Expected behavior

Get correct dates displayed, get advancement of one day when clicking, and not infinite load (if there is some data error get an information about the data error).

### Screenshots

Are already included in "*To Reproduce*".

### Desktop (please complete the following information):

 - OS: [Artix GNU/Linux](http://artixlinux.org),
 - Browser: Firefox
   - Version: 125.0b6

### Smartphone

*None.*

**Comment by marudor** [comment]
filter change. Should now be correct.
