### ISSUE TITLE
Wrong U-Bahn shown (Sendlinger Tor, München)

### ISSUE THREAD

**Issue by Ein-Tim** [marudor/bahn.expert#859]
**Describe the bug**

I have selected "Sendlinger Tor, München" under "Abfahrten ÖPNV" 
![image](https://github.com/yandevelop/Bea/assets/67682506/e3d8d5eb-f858-40b1-93fc-8deed62cfc67)

When I now tap on the extended U2, I get the link https://bahn.expert/regional/details/U%206053/2024-04-05T12:41:00.000Z?evaNumberAlongRoute=625177, which is some U-Bahn in Wien. That's not right. 
Is this an issue with bahn.expert or rather some data issue in the Bahn backend?

**Smartphone:**
 - Device: iPhone 14 Pro
 - OS: iOS 17.4.1
 - Browser: Safari

**Comment by marudor** [comment]
Backend problem for "Nahverkerhs Abfahrten"
Those will be replaces soon anyways
