### ISSUE TITLE
Messages returned by `hafas/v4/tripSearch` might not contain `txtN`

### ISSUE THREAD

**Issue by networkException** [marudor/bahn.expert#861]
**Describe the bug**

In contrast to what the OpenAPI spec enforces, messages returned by `hafas/v4/tripSearch` might not contain the `txtN` field.

I'm not sure how long the response will stay the same, here's how I found it:

`curl 'https://bahn.expert/api/hafas/v4/tripSearch' -H 'accept: application/json' -H 'content-type: application/json' --data-raw '{"time":"2024-04-17T01:39:24.870Z","searchForDeparture":true,"start":{"evaNumber":"8000105","type":"stopPlace"},"destination":{"evaNumber":"8002549","type":"stopPlace"},"via":[],"maxChanges":"-1","transferTime":"0","onlyRegional":false,"onlyNetzcard":false,"hafasProfile":"db"}' -s | jq .routes[4].segments[1].messages[7]`

which returns

```json
{
  "type": "M",
  "code": "",
  "icoX": 17,
  "txtS": "ICE 888: Göttingen->Hamburg Hbf: Information.",
  "sIdx": 1
}
```

**Comment by marudor** [comment]
Openapi no longer exists
