### ISSUE TITLE
Verschiedene Datenstände Abfahrtstafel und Detailseite des Zuges

### ISSUE THREAD

**Issue by Thulmi** [marudor/bahn.expert#864]
**Describe the bug**
Hin und wieder kommt es bei der Abfahrtstafel zu von der Detailansicht des Zuges abweichenden Datenständen.
Aufgrund der fetten Zeiten in der Detailansicht und realen Erfahrungen gehe ich davon aus, dass in der Regel die Abfahrtstafel falsche Datenstände hat.
Es trifft Regional- undFernverkehr, Fahrten, die erst einige Minuten zurückliegen und solche, die schon mehrere Stunden zurückliegen. 
Meist werden am Bahnhof veränderte Verspätungen nicht angezeigt, es kommt aber auch vor, dass ein eingekürzter Zuglauf nicht angezeigt wird (siehe Screenshots).
Die falschen Verspätungsdarstellung beobachte ich so schon mehrere Monate, der nicht angezeigte eingekürzte Zuglauf ist mir erst heute aufgefallen.

**To Reproduce**
Ich habe noch kein Muster erkannt, nach dem dieser Fehler auftritt.
Am besten bei einigen verspäteten Zügen die Details aufrufen und die Daten abgleichen.

**Expected behavior**
Die Daten sollten übereinstimmen und jeweils aktuell sein.

**Screenshots**
Beispiele von heute in Köln Hbf:
![RB48_Tafel](https://github.com/marudor/bahn.expert/assets/81866282/55133928-0633-4619-9bef-3b884620408b)
![RB48-Details](https://github.com/marudor/bahn.expert/assets/81866282/059e26ac-91f6-4992-8011-dec9d62ce629)

![S12_Tafel](https://github.com/marudor/bahn.expert/assets/81866282/232e69d0-dbdd-483c-93bb-edb519c259d2)
![S12-Details](https://github.com/marudor/bahn.expert/assets/81866282/da36db10-8bd9-4d62-8a5b-ad95f09804eb)

**Comment by marudor** [comment]
Andere Datenquelle. Lässt sich nichts machen.
