### ISSUE TITLE
Time is resolved wrongly in browser

### ISSUE THREAD

**Issue by faule-sofakatze** [marudor/bahn.expert#865]
**Describe the bug**
When looking up a train the shown time in the left column is shown in UTC instead of showing the correct (localized) time of the train schedule.
This seems to be browser-specific. It works in Chrome (correct time), it does work in DuckDuckGo Browser (correct time) in Android but it fails in libreWolf (UTC) on Linux. Chrome and libreWolf where tested on the same system.

**To Reproduce**
0. Use browser libreWolf
1. Go to bahn.expert and check for a train (train search)
2. Enter correct date and train number. I used ICE595 on the 28th of April for testing
3. Observe the start / stop times on the left of the route.

**Expected behavior**
The correct, locallized time according to the schedule of the train.

**Screenshots**
taken in libreWolf is attached.

**Desktop (please complete the following information):**
 - OS: manjaro linux, stable
 - Browser: current version of libreWolf (not ok); current version of Chrome (ok)

**Additional context**
Reproduceable with other trains, not sure if this is intended.
![bahn_expoert_ICE595_Laptop](https://github.com/marudor/bahn.expert/assets/111574990/a3612e20-d49d-478e-bece-d3a261775203)

**Comment by marudor** [comment]
Time is always your time. Its whatever your browser says is your timezone.
