### ISSUE TITLE
Einchecken in Travelynx schlägt fehl

### ISSUE THREAD

**Issue by 3D-Schorsch** [marudor/bahn.expert#873]
**Describe the bug**

**To Reproduce**
- Ich habe eine Route im Nahverkehr eingegeben.
- Wenn man jetzt versucht die Fahrt in Travelynx einzuchecken kommt die Fehlermeldung, dass es die Weiterleitung nicht eindeutig ist. 

**Expected behavior**
bahn.expert checkt an der Richtigen Stelle in Travelynx ein. Heißt also das der Link in Bahn. Expert die Startbezeichnung richtig mitgibt. 

**Screenshots**
![IMG_6476](https://github.com/marudor/bahn.expert/assets/85443407/1d8a5943-80e8-4197-a19c-1a5324981325)

 
**Smartphone (please complete the following information):**
 - Device: iPhone8
 - OS: iOS16.6
 - Browser safari
 - Version 

**Additional context**

**Comment by marudor** [comment]
Travelynx handlet Nahverkehr völlig anders. Ist aber fachlich eig. kein Problem von bahn.expert.
Ich machs hier absichtlich zu.
