### ISSUE TITLE
Werdau bug 

### ISSUE THREAD

**Issue by Joplo918** [marudor/bahn.expert#874]
**Describe the bug**
Wenn man über die Zugläufe auf Werdau (bspw. Bei der s5x) klickt gelangt man auf die Abfahrtstafel von Werder(Havel) 

**To Reproduce**
1. Go to 'Abfahtstafel von Zwickau (S.) Hbf'
2. Click on 'S5X (sodass man aber im Menü der Abfahrtstafel bleibt)'
3. Click on 'Werdau' 

**Expected behavior**
Richtige Abfahrtstafel wird gezeigt 

**Screenshots**

https://github.com/marudor/bahn.expert/assets/170650947/3f30b122-c74c-43d2-b902-01253b5e9784

**Smartphone (please complete the following information):**
 - Device: [e.g. Huawei p40 pro]
  - OS: [e.g. EMUI 12.0.0.370]
 - Browser [e.g. Huawei Browser]
 - Version [e.g. 14.0.5.302]

**Comment by marudor** [comment]
fixed
