### ISSUE TITLE
Abfahrzeiten von Stadtroda über Suche nicht abrufbar

### ISSUE THREAD

**Issue by IceBro9** [marudor/bahn.expert#879]
**Describe the bug**
Wenn man nach dem Halt Stadtroda sucht und anklickt, erscheint nur "Die Abfahrt existiert nicht"

**To Reproduce**
1. Go to 'bahn.expert'
2. Suche nach "Stadtroda"
3. Klicke auf das Ergebnis "Stadtroda

**Expected behavior**
Die Abfahrtszeiten des Bahnhofs Stadtroda zu sehen

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [125]

**Smartphone (please complete the following information):**
 - Device: [Samsung A54]
 - OS: [Android 14]
 - Browser [Webapp]

**Additional context**
Der direkte Aufrufe mithilfe der DS100 Abkürzung funktioniert interessanterweise:
https://bahn.expert/USR

**Comment by marudor** [comment]
fixed
