### ISSUE TITLE
Kiosk mode for use in cafes, restaurants, etc.

### ISSUE THREAD

**Issue by Intubun** [marudor/bahn.expert#882]
**Is your feature request related to a problem? Please describe.**
A way to use bahn.expert for use as a train station arrival and departure board within cafes and restaurants would be nice. Mostly since the "Web Bahnhofstafel" from the DB is not good in terms of data and bahn-expert is not yet useable with sometimes popup messages from marudor.

**Describe the solution you'd like**
Maybe removing the top bar with the current train station and just showing the trains. maybe configurable via a cookie? Also messages (like to one to the european election results) that pop up arent displayed across the whole screen and maybe just on a part so the departures are still visible without human intervention. Maybe also make some advertisement to bahn.expert visible on screen, because I actually think it is a perfect app for every train traveler.

**Describe alternatives you've considered**
The only alternative is to use the "Web Bahnhofstafel" from the DB with an offical permit.

**Comment by Ein-Tim** [comment]
You may consider using https://github.com/derf/db-fakedisplay.

**Comment by marudor** [comment]
Example: https://bahn.expert/FF?politic=1&noHeader=1
politic=1 removes the popup, noHeader removes the top bar.
