### ISSUE TITLE
Train stations disappeared "Die Abfahrt existiert nicht"

### ISSUE THREAD

**Issue by WI77I** [marudor/bahn.expert#884]
**Describe the bug**
Trying to access the train station "Dresden-Trachau" or "Dresden-Pieschen" leads to the error "Die Abfahrt existiert nicht".

I doesnt matter if i try to access it via bookmark or search.

I tried some nearby train stations and they do seem to work properly. 

**To Reproduce**
1. Go to 'https://bahn.expert/Dresden-Pieschen'
2. See error

**Expected behavior**
Selecting the station from my favorites or via search leads to the station informations.

**Screenshots**
![Screenshot_20240613-170415](https://github.com/marudor/bahn.expert/assets/172618485/3e74598c-8a7e-4be8-b2f2-c2d9fe1b6f86)

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.5
 - Browser: chrome
 - Version: 125.0

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6 Pro
 - OS: Android 14
 - Browser: current firefox and chrome versions

**Comment by marudor** [comment]
fixed - sadly there is an upstream error right now that triggers this.
