### ISSUE TITLE
Frankfurt(Main)Hbf doesn't exists

### ISSUE THREAD

**Issue by StareInTheAir** [marudor/bahn.expert#885]
**Describe the bug**
Frankfurt Hbf doesn't work anymore

**To Reproduce**
1. Go to https://bahn.expert/
2. Click on Frankfurt(Main)Hbf
3. See error "Die Abfahrt existiert nicht"

**Expected behavior**
I want to see trains leaving Frankfurt Hbf :)

**Screenshots**
![Screenshot 2024-06-24 at 16 01 06](https://github.com/marudor/bahn.expert/assets/2929278/4b3b3bca-967d-4837-a2fc-fa9d63f3a603)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox
 - Version 127

**Additional context**
Other Frankfurt stations still work, only Hbf affected

**Comment by marudor** [comment]
Fixed - There is an upstream data problem that sometimes returns nothing for a specific query. Combined with my caching it might result in caching an empty result for a valid stopPlace name :/
