### ISSUE TITLE
Falsches Rollmaterial bei Ersatzfahrten

### ISSUE THREAD

**Issue by omia** [marudor/bahn.expert#888]
**Describe the bug**
Bei Ersatzfahrten mit anderem Rollmaterial wird die Zuginfo(pdf) des Original Materials angezeigt.
In dem Beispiel hier in den Screenshots fährt ein ICE1 für einen IC2 aber es wird die PDF für den IC2 angezeigt.

**To Reproduce**
1. Suche einen Ersatzzug mit anderem Rollmaterial
2. Falsche Rollmaterialinfo wird angezeigt.

**Expected behavior**
Anzeige des Richtigen Rollmaterials.

**Screenshots**
![image](https://github.com/marudor/bahn.expert/assets/7889102/85f2b7ef-8a57-497d-a164-1d5bea93e260)

**Additional context**
Dieser Fehler tritt in mehreren Browsern und auf unterschiedlichen Geräten auf.

**Comment by marudor** [comment]
Hier wird aber laut API auch ein ICE2 gefahren. => Ich zeig auch das an.
Ist also korrekt in der Hinsicht das die Wagenreihung für nen ICE 2 ist.

**Comment by omia** [comment]
Da ist auch ein ICE2 gefahren die Ansicht war richtig. Aber wie beschrieben wenn man auf das Blaue ICE2 (BR402) kligt hat man die PDF des IC2 bekommen.

**Comment by marudor** [comment]
Dann steht aber auch in den Daten das es nen IC2 ist wohl? KAnns mir aber nicht vorstellen (aber auch nicht mehr nachstellen)
Denn der source code ist da sehr eindeutig.
Habs nicht früh genug gesehen - gerne neu aufmachen wenns wieder auftritt.
