### ISSUE TITLE
Color Coding

### ISSUE THREAD

**Issue by EckhardM** [marudor/bahn.expert#891]
Ich fände es besser, wenn die Farbgebung der Verspätungen abgestuft wäre. Denn es macht einen Unterschied, ob ein Zug eine oder 100 Minuten verspätet ist. Mal so als Idee: Pünktlich = Grün, bis +5 blau, bis +15 Gelb, bis +60 Rot, darüber violett.

**Comment by marudor** [comment]
duplicate of #858
