### ISSUE TITLE
Zeigt Halte ohne Aus-/Einstieg ohne weitere Info

### ISSUE THREAD

**Issue by waldiTM** [marudor/bahn.expert#892]
**Describe the bug**
Ein Zuglauf kann Halte ohne Ein- oder Ausstieg enthalten (was relativ oft passiert, ICE in Hamburg-Harburg z.B.). Die DB-Auskunft zeigt diese Info korrekt an.

Es können aber auch Betriebshalte komplett ohne Ein- und Ausstieg enthalten sein. Diese Halte werden von der DB komplett unterschlagen, da für Kunden uninteressant. bahn.expert zeigt diese wie ganz normale Halte an, außer das z.B. Auslastungsinformationen fehlen.

**To Reproduce**
See stop at "Elsterwerda" for [IC 2048](https://bahn.expert/details/IC%202048/2024-07-12T05:54:22.347Z/?station=8010085)

**Screenshots**
![bahn expert_details_IC%202048_2024-07-12T05_54_22 347Z__station=8010085](https://github.com/user-attachments/assets/5730b18c-64af-4ce6-bda3-6a4e404c43b1)

**Comment by marudor** [comment]
Das ist absicht. Das "Kein Ausstieg" "Kein Einstieg" flag ist eine tarifsache.
Du darfst dort ein/aussteigen. => ich zeigs an.

**Comment by waldiTM** [comment]
Danke fürs fixen. Wobei das schon gut in #896 versteckt ist. Siehe https://github.com/marudor/bahn.expert/pull/896/commits/ef3d48f790bf08d81157c6e7aaa938213c605144.
