### ISSUE TITLE
Grund für Verspätungen

### ISSUE THREAD

**Issue by flschnepf** [marudor/bahn.expert#897]
Hallo, ich frage mich, wie du die Gründe für die Verspätungen auf deiner Seite bekommst und was die Uhrzeit davor aussagt. Ist das die Zeit, zu der die Meldung einging?
Ich habe selbst schon versucht, die Gründe aus dem hafas-client zu ziehen, bekomme aber nur die remarks vom Typ "hint" und dachte, ich frage hier nach.

**Comment by Ein-Tim** [comment]
HAFAS liefert meines Wissens nach die Gründe nicht, nur IRIS.

**Comment by marudor** [comment]
Genau, Uhrzeit ist die Zeit der Meldung (letzte, es wird dedupliziert)
Afaik stehts im Hafas wie @Ein-Tim sagt nicht korrekt. Ich nutz aber fast kein HAFAS mehr, bin da also nicht mehr auf dem neusten Stand
