### ISSUE TITLE
Wagenreihungen im Regionalverkehr broken?

### ISSUE THREAD

**Issue by SpielenmitLili** [marudor/bahn.expert#902]
**Describe the bug**
Wagenreihungen von Nahverkehrszügen werden nicht mehr unter Detailansicht angezeigt (Zur Gegenprüfung sind sie im DB Navigator da)

**To Reproduce**
1. Menü ausklappen
2. Zugsuche öffnen
3. "Nur Fernverkehr, nur aktuelle Züge" abwählen
4. Regionalverkehrszug aussuchen (getestet bei (4102, 4100, 12600, 12602)

**Expected behavior**
Die Wagenreihung des Zuges bei der die Tz und weitere Infos zu sehen sind sollte sichtbar sein.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Z Flip 4
 - OS: Android 14 mit OneUi 6.1
 - Browser Chrome
 - Version 127.0.6533.103

**Additional context**
Bei Fernverkehrszügen scheint das Problem nicht vorhanden zu sein

**Comment by marudor** [comment]
fixed mit #903 
FV Züge waren auch betroffen.
