### ISSUE TITLE
Site ignores disambiguating journey ID when provided with an ambiguous train number

### ISSUE THREAD

**Issue by deingithub** [marudor/bahn.expert#912]
**Describe the bug**
Related to https://github.com/derf/travelynx/issues/158, I tried to replicate the patch described there for my own project and ran into this issue:  when constructing a journey details link with a train number (as needed to get RIS::Journeys realtime data, apparently) bahn.expert will ignore a provided journey ID and pick a seemingly random transport with the same train number.

**To Reproduce**
Compare two journey details links with the same journey ID:
One with a train number: https://bahn.expert/details/Bus%20227/1724600460000?jid=2|%23VN%231%23ST%231724349974%23PI%230%23ZI%23916924%23TA%231%23DA%23250824%231S%238505973%231T%231729%23LS%238505767%23LT%231755%23PU%2380%23RT%231%23CA%23Bus%23ZE%23118%23ZB%23Bus%20%20118%23PC%235%23FR%238505973%23FT%231729%23TO%238505767%23TT%231755%23 
![Screen Shot 2024-08-25 at 17 32 55](https://github.com/user-attachments/assets/92b54257-4e3a-4813-a32e-1bd091c9ace0)

And one without: https://bahn.expert/details/0/1724600460000?jid=2|%23VN%231%23ST%231724349974%23PI%230%23ZI%23916924%23TA%231%23DA%23250824%231S%238505973%231T%231729%23LS%238505767%23LT%231755%23PU%2380%23RT%231%23CA%23Bus%23ZE%23118%23ZB%23Bus%20%20118%23PC%235%23FR%238505973%23FT%231729%23TO%238505767%23TT%231755%23
![Screen Shot 2024-08-25 at 17 43 11](https://github.com/user-attachments/assets/12ecb46f-ae81-45b1-93ef-5bec4422685c)

**Expected behavior**
Both links should display the same (second) journey.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: FF
 - Version: 127

**Additional context**
Maybe it would be possible to fetch the RIS::Journeys "bolded" real-time data even without the train number being in the link? From the HAFAS journey ID it should be possible to get the needed train number even if it's not included in the link.

**Comment by marudor** [comment]
thats not journeyID for RIS::Transports. JID is for HAFAS an does not work very well in the past => if nothing is found I fallback to the usual process that just doesn't work very well for buses.
