### ISSUE TITLE
Züge können bei Zugsuche nicht mehr gefunden werden (Nahverkehr)

### ISSUE THREAD

**Issue by SpielenmitLili** [marudor/bahn.expert#913]
**Describe the bug**
Ich bin in letzten Tagen bereits öfter auf das Problem gestoßen, dass ich nach Zügen suchen wollte, deren Zugnummern ich auswendig kenne und weiß, dass sie fahren, diese allerdings mit der Zugsuche von bahn.expert nicht mehr gescheit finden konnte. Ich werde hier mit als Beispiel mit Zug 4134 arbeiten, das Problem tritt jedoch auch bei anderen Zügen auf. Im DB Navigator wird der Zug ganz normal gelistet (hier habe ich ein Screenshot von der Webseite der Bahn zum Vergleich eingefügt)

**To Reproduce**
1. bahn.expert aufrufen und Seitenleiste ausklappen
2. Zugsuche auswählen
3. "Nur Fernverkehr, nur aktuelle Züge" abwählen
4. Zugnummer 4134 eingeben

**Expected behavior**
Der Zug 4134 sollte in der Liste der Züge/Busse zur Auswahl vorhanden sein, sodass man den Zug im bahn.expert öffnen kann. 

**Screenshots**
![image](https://github.com/user-attachments/assets/16d6d78e-b001-4645-abcb-469ff4d3ef77)
![image](https://github.com/user-attachments/assets/b6b525ac-f1db-40a0-8297-1b2afb5e6835)

Getestet auf folgenden Geräten, scheint eher ein globales Problem zu sein.
**Desktop:**
 - OS: Windows 10 Enterprise LTSC
 - Browser Chrome
 - Version 127.0.6533.120

**Smartphone:**
 - Device: Samsung Galaxy Z Flip 4
 - OS: Android 14
 - Browser Chrome
 - Version 127.0.6533.103

**Additional context**
Generell scheint es die Züge in bahn.expert zu geben, da die in der Abfahrtstafel erscheinen und darüber aufgerufen werden können. Also scheint es sich bei dem Problem explizit um etwas was mit der Suche zu tun hat zu handeln. (vielleicht zu viele Busse? Fix wäre dann maybe Schienenfahrzeuge zu priorisieren in der Ansicht oder ne Möglichkeit zu scrollen hinzuzufügen)

**Comment by marudor** [comment]
Hat mit der "neuen" (besseren) Suche zu tun - die findet jetzt "leider" sehr viel mehr.
Ich überleg es mir. Würde im ersten Schritt ein Schalter für "nur Schiene" helfen?
Busse und Straßenbahnen sind schwierig. Und der aktuelle Filter ist sehr unklar was er genau tut weil der historisch fürs HAFAS da ist - das nutz ich aber nur noch in Ausnahmefällen.

**Comment by SpielenmitLili** [comment]
Ein "nur Schiene"-Filter würde zumindest mir und ein paar Menschen die ich kenne helfen.
Da man in der Regel mit bahn.expert ja nach Fahrten mit Zügen sucht (kenne ich zumindest bei mir so)
