### ISSUE TITLE
Train missing at station view at Graz

### ISSUE THREAD

**Issue by weaselp** [marudor/bahn.expert#918]
**Describe the bug**
At Graz Hbf (https://bahn.expert/Graz%20Hbf), not all trains that arrive at Graz are shown.

**To Reproduce**

Compare https://bahn.expert/Graz%20Hbf to the arrivals at Graz at https://fahrplan.oebb.at/webapp/#!P|SQ!H|

**Expected behavior**

I'd expect to see more of the trains that oebb schows to be visible also on bahn.expert.
For instance, IC 515 goes to Graz but is missing at the station view.

**Screenshots**

![bahn-expert-and-a-train](https://github.com/user-attachments/assets/97a8ca6c-e511-4705-b2f0-1c63981f51a1)
![arrivals-oebb](https://github.com/user-attachments/assets/f172351e-2bb5-4385-b7a1-86500c1f0dff)

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Browser: firefox 115.14.0esr

**Comment by marudor** [comment]
Only DB Backends are supported. So very few trains outside of Germany. This is on purpose.
