### ISSUE TITLE
default Filter settings

### ISSUE THREAD

**Issue by tciberlin** [marudor/bahn.expert#926]
Hi, leider bleiben seit kurzem die Standard Filtereinstellungen nicht gespeichert. Sobald die Seite Bahn.expert erneut aufgerufen wird, werden die zuvor eingestellten Filtereinstellungen (bspw. Keine S-Bahn) wieder zurückgesetzt.

**Comment by marudor** [comment]
Geht mit 1e2964b wieder
wird nachher deployed
