### ISSUE TITLE
Save as defalault bug 

### ISSUE THREAD

**Issue by Joplo918** [marudor/bahn.expert#930]
**Describe the bug**
Save es default funktion defekt

**To Reproduce**
1. Go to 'Abfahrten'
2. Click on 'drei Striche'
3. Click on 'Filter' 
4. Click on 'Ice abfählen' 
5. Click on 'save as default' 
6. Click on 'F5/refresh page' 
7. Click on '1. 2. Und 3. Wiederholen' 
8. See error

**Expected behavior**
ICE sollte abgewählt sein

**Smartphone (please complete the following information):**
 - Device: [e.g. Huawei P40 pro]
 - OS: [Android Emui 12]
 - Browser [Huawei Browser]
 - Version [e.g. 14.0.5]

**Additional context**
Probiert am Bsp Dresden Hbf sollte aber überall so sein

**Comment by marudor** [comment]
Gute Frage warum das nicht tut...
Lokal gehts, im Test gehts. Auf Prod nicht

**Comment by Joplo918** [comment]
Jetzt geht's glaube wieder, zumindest sahs grad danach aus

**Comment by marudor** [comment]
Ah. Hab den fix einfach nicht deployed gehabt...
