### ISSUE TITLE
Sortierung nach Echtzeit unwirksam

### ISSUE THREAD

**Issue by lukas-kidin** [marudor/bahn.expert#931]
**Describe the bug**
Obwohl in den Einstellungen die Option "Sortiere Abfahrten nach Echtzeit" aktiviert ist, sind die Abfahrten nach Planzeit sortiert.

**To Reproduce**
1. Wähle die Einstellungen wie im Screenshot
2. Öffne einen Abfahrtsmonitor, bei dem Züge verspätet sind

**Expected behavior**
Die Züge sind nach Echtzeit sortiert.

**Screenshots**
![Screenshot_20240919-140333](https://github.com/user-attachments/assets/90b82ebd-e33f-4b99-b9ad-925476f7eebb)
![Screenshot_20240919-140343](https://github.com/user-attachments/assets/8407e446-40ad-4903-91b1-7606c7fe2fec)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6pro
 - OS: Android 14
 - Browser Firefox

**Additional context**
Fehler tritt erst seit kurzem auf

**Comment by marudor** [comment]
Ah - da hab ich die Tage was dran gemacht. Weiß vermutlich warum (dafür hab ich keinen testcase)

**Comment by marudor** [comment]
mit https://github.com/marudor/bahn.expert/commit/984d8005f2941a42cca2e56dbf8a1895bee730d2 fixed. (Deployed dann nachher)
