### ISSUE TITLE
Falsche Busverbindung (Anzeige anders als ausgewählt) bei "Nahverkehr Abfahrten"

### ISSUE THREAD

**Issue by frie** [marudor/bahn.expert#937]
**Describe the bug**
Bei Klick auf eine der angezeigten Busverbindungen für eine Station wird manchmal eine andere als die ausgewählte angezeigt. Meistens aber doch die korrekte Verbindung. Besondere Bedingungen dafür, dass der Fehler auftritt, konnte ich bisher nicht herausfinden. Manchmal werden auch Verbindungen aus komplett anderen Regionen / Verbünden angezeigt.

**To Reproduce**
1. Auswahl **Nahverkehr Abfahrten**
2. Auswahl **Reinheim(Odenw)** aus den Favoriten (morgens 8:12 Uhr)
3. Klick auf **Bus 693** mit Abfahrt 8:37
4. Angezeigt wird dann der Streckenverlauf für den  **Bus RH (346)**, Abfahrt 12:18 ab Darmstadt, von Reinheim 13:03
5. Gleiche Art Fehler bei Klick auf **Bus RH** mit Abfahrt 8:33, hier wird dann **Bus EV (356)** angezeigt, der irgendwo in Franken herum fährt

**Expected behavior**
Anzeige des Streckenverlaufs für den ausgewählten Bus

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium, Firefox (scheint keine Rolle zu spielen)
 - Version spielt offensichtlich keine Rolle

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy XCover 4
 - OS: Android 9
 - Browser Chrome
 - Version spielt offensichtlich keine Rolle

**Additional context**
Evtl. ist die Anzeige der verfügbaren Verbindungen bei der **Nahverkehr Abfahrten** falsch. Die Verbindung ab Reinheim 8:37 sehe ich nicht bei der DB und auch nicht beim regionalen Verbund (RMV). Die Abfahrt 9:12 sehe ich aber überall, bahn.expert zeigt hier aber auch wieder eine andere Fahrt ah, als die ausgewählte (in diesem Fall wieder wie für die Verbindung 8:37 den **Bus RH (346)**). Das ganze ist natürlich von der Tageszeit abhängig, lässt sich nicht mehr repoduzieren wenn der _Bus weg_ ist

**Comment by frie** [comment]
Anscheinend nicht reproduzierbar, heute eine Stichprobe ohne Fehler. Falls sich das bestätigt, schließe ich das Ticket

**Comment by Ein-Tim** [comment]
- #859 beschreibt ein sehr ähnliches Problem, @marudor schrieb dort, dass es sich um ein bekanntes Problem handelt und sich bei den Nahverkehrsabfahren bald eh was ändern wird

**Comment by marudor** [comment]
"bald" ist eine Zeiteinheit zwischen jetzt und in 2 Jahren bei mir, aber ja. Das wird sich ändern.
Und ja, ist bekannt.

**Comment by frie** [comment]
> "bald" ist eine Zeiteinheit zwischen jetzt und in 2 Jahren bei mir, aber ja. Das wird sich ändern. Und ja, ist bekannt.

Ich habe kein Problem mit dem close, aber wenn demnächst jemandem der gleiche Fehler auffällt, gibt's dann wieder eine gut gemeinte neue Meldung. Von daher wäre es übersichtlicher, mit dem close bis _jetzt oder i 2 Jahren_ zu warten
