### ISSUE TITLE
Nicht funktionierende Identifier in "Zugläufe" entfernen.

### ISSUE THREAD

**Issue by MarkMcWire** [marudor/bahn.expert#939]
Folgende Identifier haben keine Auswirkung auf die Zugauswahl und sollten m.E. als überflüssig entfernt werden:

401.LDV -> hat keine Wirkung, 401.9 erfüllt im Prinzip die gleiche Funktion und gibt auch ein Suchergebnis
ab kommenden Jahr sollen eh nur noch 9-teilige (gekürzte) ICE1 im Fahrgastbetrieb eingesetzt werden, daher ist hier eine Unterscheidung auch nicht länger notwendig.

411.S1 sowie 411.S2 -> keine Wirkung  / kein Suchergebnis
403.S1 sowie 403.S2 -> keine Wirkung / kein Suchergebnis

403.R -> alle 49 noch existierenden Triebzüge der Baureihe 403 wurden umgebaut, daher ist eine Abgrenzung von "Redesign" zu nicht-"Redesign" nicht länger notwendig
406.R -> keine Wirkung, es gibt mit Tz 4651 eh nur ein einziges Exemplar und keinen festen Umlaufplan dafür

MET -> Züge existieren nicht länger
410.1 -> ICE-S werden nicht im Fahrgasteinsatz benutzt, daher ist eine Suche nach dieser Baureihe für den öffentlichen Regelbetrieb überflüssig.

**Comment by marudor** [comment]
Tatsächlich ist wenn dann 401.LDV korrekt. Es gibt/gab gekürzte 401 die nicht LDV sind. Und naja... Wenn ich alles schon umsetze was theoretisch "soll" fehlen viele Features.
Die Identifier sind nicht umsonst markeirt als "von mir erdacht" (Und das ganze feature ist als "ohne support" markiert)
Eh noch nicht klar ob ich die Daten fürs Fahrplanjahr 2025 bekomme. Kann also auch sein das das Feature noch mal verschwindet.

Ich schliess das hier bewusst mal. Das sind halt technische Identifier die ich im code brauche. Wenn überhaupt müsste ich die mal updaten weil z.B. neben IC2.TRE (Was die IC2 Twindexx sind aber der Witz mit "TRE = Teppich RE") auch die IC2.KISS gibt. Wenn auch nicht viele.

Insgesamt ist das Planwagenreihungsding halt viel orakel.
