### ISSUE TITLE
Fehler bei Anzeige "gleicher Bahnsteig" in der Anschlussliste

### ISSUE THREAD

**Issue by SpielenmitLili** [marudor/bahn.expert#947]
**Describe the bug**
Es handelt sich um einen interessanten Fehler bei den Anschlüssen eines Zuges. Der Fehler tritt auf, wenn Anschlüsse für "andere Bahnhöfe" mit angezeigt werden.

Das ist zum Beispiel bei "Konz" der Fall. Dort werden in den Anschlüssen ebenfalls die Bahnhöfe "Konz Mitte" und "Kreuz Konz" angezeigt, obwohl diese weiter entfernt liegen.

Der Fehler ist nun, dass bei Zügen aus Trier kommend die auf Gleis 1 halten (4122 zum Beispiel) bei Zügen in Kreuz Konz und Konz Mitte "gleicher Bahnsteig" angezeigt wird, obwohl das faktisch falsch ist (da die Züge in einem anderen Bahnhof halten)

So ist als Beispiel bei dem zuvor genannten 4122 die RB 82 (12177) ein Anschlusszug. Diese RB fährt aber in Konz Mitte von Gleis 1 ab statt in Konz wie das bei 4122 der Fall ist. Damit sollte da nicht "gleicher Bahnsteig" dabei stehen.

![Screenshot_20241003_141948_Chrome](https://github.com/user-attachments/assets/4745f85c-bb37-4224-97e0-967f5a123f58)

**Comment by marudor** [comment]
fixed with 70771a0ff7eebb90e70d55bdd735e724154cd3c5
