### ISSUE TITLE
Live-Daten ICE 90 werden nicht angezeigt (am 05.10. und 04.10.2024)

### ISSUE THREAD

**Issue by karlgrotheer** [marudor/bahn.expert#949]
**Describe the bug**
In der Abfahrtstafel wird die Verspätung des ICE 90 angegeben, in der Detailansicht des Zuges steht jedoch keine Live-Prognose, sondern nur der Fahrplan.

**To Reproduce**
1. HG oder anderen Bahnhof öffnen
2. ICE 90 suchen
3. Zug anklicken
4. Fehler sehen

1. Zugsuche öffnen
2. 90er öffnen
3. Fehler sehen

**Expected behavior**
Aktuelle Daten, ob pünktlich oder nicht

**Screenshots**
![Screenshot 2024-10-05 191525](https://github.com/user-attachments/assets/c6f5e4dc-5269-4ba2-aeeb-854b82ca103e)

**Comment by tciberlin** [comment]
Das liegt wohl eher daran, dass der Zug zweimal im System mit unterschiedlichen ZugIDs hinterlegt ist. ![image](https://github.com/user-attachments/assets/26266c05-b7b3-43d6-9c1a-516d3c6d17c3)

![image](https://github.com/user-attachments/assets/636c2cea-8364-4230-aa0e-be644923a2ee)

![image](https://github.com/user-attachments/assets/be834964-d336-4b0a-ae48-614485687211)

**Comment by marudor** [comment]
Danke fürs nachschauen. Wenn die Daten die ich mit bahn.expert kacke sind kann ich oft leider nichts machen.
Daher can't fix und ich schliess mal.
