### ISSUE TITLE
"Zug Wendet Auf" verlinkt Zug mit Zugnummer von gestern.

### ISSUE THREAD

**Issue by TheTwix** [marudor/bahn.expert#952]
**Describe the bug**
Der Link "Zug Wendet auf" verlinkt einen Zug mit der richtigen Zugnummer aber von gestern.

**To Reproduce**
1. Go to https://bahn.expert/details/RE%2091723/2024-10-16T10:47:00.000Z?evaNumberAlongRoute=8006713
2. Click on 'Wendet auf RE 89708'
3. See train from yesterday

**Expected behavior**
I would have expected to be linked to the train from today.

**Screenshots**
![bahn_expert_r6](https://github.com/user-attachments/assets/a5b8428c-66e9-41bd-8ac3-5a2281783f48)
![bahn_expert_r6_yesterday](https://github.com/user-attachments/assets/a0e3cfea-fdb5-4b10-9d1d-63a3040f6e8e)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 131.0.2

**Smartphone (please complete the following information):**
 - OS: Android
 - Browser Fennec
 - Version 129.0.2

**Comment by marudor** [comment]
Cache Proble, war auch angekündigt.
Sollte jetzt viele weitere Fälle abdecken. Bitte neues Ticket wenns wieder auftritt
