### ISSUE TITLE
Suche nach Zugnummern mit öpnv

### ISSUE THREAD

**Issue by Extravertiert** [marudor/bahn.expert#953]
Ich wollte den Sachstand zum RE1 ermitteln.
Da nur Ziffern eingegeben werden können, demzufolge nur die 1.
Die Treffermenge zeigt keinen RE1 an.

**Comment by Extravertiert** [comment]
![Screenshot_20241016_212335_com android chrome](https://github.com/user-attachments/assets/13ec141e-f9d8-4758-8d50-f2ce1c947bd3)

**Comment by marudor** [comment]
Ich brauch Zugnummern, keine Linien.
1 ist die Linie, nicht die Zugnummer.
REs brauchen dazu nicht "ÖPNV berücksichtigen" - das ist "heavy metal"
