### ISSUE TITLE
Clicking on "Buddestraße, Krefeld" when coming from "Tram 044" route overview results in "Unbekannter Fehler".

### ISSUE THREAD

**Issue by dreirund** [marudor/bahn.expert#959]
**Describe the bug**  
Clicking on "Buddestraße, Krefeld" when coming from "Tram 044" route overview results in "Unbekannter Fehler".

**To Reproduce**  
1. Open [Overview of the trip of "STR 044" from "Rheinhafen, Krefeld" on 2024-10-28, departure 12:05](https://bahn.expert/details/1729764300000?jid=2%7C%23VN%231%23ST%231729541757%23PI%230%23ZI%232186815%23TA%230%23DA%23241024%231S%23658703%231T%231205%23LS%23658733%23LT%231222%23PU%2380%23RT%233%23CA%23STR%23ZE%23044%23ZB%23STR%20%20044%23PC%238%23FR%23658703%23FT%231205%23TO%23658733%23TT%231222%23)
2. Click on the [link for the stop "[Buddestraße, Krefeld](https://bahn.expert/Buddestra%C3%9Fe%2C%20Krefeld)"
3. See error "Unbekannter Fehler"

**Expected behavior**  
See upcoming departures for "Buddestraße, Krefeld", or a clear error description

**Screenshots**  

---

![image](https://github.com/user-attachments/assets/609cc8e6-eace-4a9d-9c8e-2a198eb71511)

---

**Desktop (please complete the following information):**
 - OS: [Artix GNU/Linux](http://artixlinux.org/)
 - Firefox
 - 132

**Further information**  
The "Tram 044" actually is a replacement bus service.

**Comment by marudor** [comment]
Will be solved once I change the departures to a new API. Won't fix this in the old system.
