### ISSUE TITLE
Zwei Loks hintereinander (Wagenreihung)

### ISSUE THREAD

**Issue by ComputerGod63** [marudor/bahn.expert#960]
![Screenshot 2024-10-25 083032](https://github.com/user-attachments/assets/61469e9f-8a10-404c-b801-f513f2628581)

Wenn man die Wagenreihung vom RE 3 (Passau-München) abruft (in diesem Fall RE 4064), erscheinen zwei Lokomotiven hintereinander.
(Wie bei dem Bild oben).

Ich verwende Windows 11 und den Microsoft Edge Browser Version 130.0.2849.46 (Offizielles Build) (64-Bit).

**Comment by marudor** [comment]
Teilweise ist das korrekt.
Allerdings gibt es auch ein upstream (also DB) bug der genau das hier erzeugt. Kann ich nicht ändern.
