### ISSUE TITLE
Verspätungsdaten im Fahrtverlauf nicht korrekt

### ISSUE THREAD

**Issue by vt642** [marudor/bahn.expert#961]
Seit heute (26.10.2024) werden Verspätungen zwar auf der Abfahrtstafel-Ansicht korrekt angezeigt, im Fahrtverlauf dann aber nicht - entweder fehlen sie ganz oder es stehen nur die am Fahrtbeginn generierten Prognosen dort. Fettgedruckte (bestätigte) Zeiten nur für wenige Stationen. Betroffen sind allerdings nicht alle Züge, wohl aber ein sehr großer Teil.

**Comment by marudor** [comment]
Upstream Problem bekannt. Dauert inzwischen so lange das gleich nen Text kommt.
