### ISSUE TITLE
Kein Bug, aber Schreibfehler in https://bahn.expert/about

### ISSUE THREAD

**Issue by baumenia** [marudor/bahn.expert#962]
**Describe the bug**
"Es ist das Privatprojekt von mir und **spiegel** niemals Meinungen der Deutschen Bahn oder anderen Verkehrsunternehmen wieder.
 
**To Reproduce**
1. go to [the about page](https://bahn.expert/about)

**Screenshots**
![image](https://github.com/user-attachments/assets/a7d7c2cb-36f5-4620-8191-49228ce3ef03)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [vivaldi (reports itself as chrome)]

**Comment by ComputerGod63** [comment]
Hallo,
das ist kein Tippfehler weil es ein Verb sein soll!

LG ComputerGod63

**Comment by ComputerGod63** [comment]
Nein, weil es heißt "ich spiegel" somit ist es kein Rechtschreibfehler.

**Comment by Ein-Tim** [comment]
"spiegel" bezieht sich hier auf das Privatprojekt, deshalb muss es "spiegelt" heißen.

**Comment by ComputerGod63** [comment]
Ist doch kein Weltuntergang 🤦‍♂️

**Comment by Ein-Tim** [comment]
Das behauptet ja auch keiner ;-)

@baumenia hat das gemeldet, @marudor weiß also bescheid und kann nun entscheiden ob das geändert wird oder nicht.

**Comment by h01ger** [comment]
Danke auch von mir! und "spiegelt" und "wider" indeed. :)
