### ISSUE TITLE
Keine Ist-Daten

### ISSUE THREAD

**Issue by vt642** [marudor/bahn.expert#978]
Derzeit werden keine Ist-Daten (fettgedruckt) angezeigt, nur die Prognosen.

Beispielsweise die aktuellen Abfahrten für Frankfurt(M) Hbf.

**Comment by vt642** [comment]
Auch die Anzeige von Verspätungsdaten aus der Vergangenheit ist derzeit nicht möglich.

**Comment by marudor** [comment]
Funktioniert einwandfrei bei mir.
