### ISSUE TITLE
Verspätungsstatistik eines Zuges

### ISSUE THREAD

**Issue by uneko1st** [marudor/bahn.expert#980]
Über die Zugnummernsuche und Eingabe eines vergangenen Datums ist schon jetzt die historische Einzelanzeige mit den jeweiligen Abfahr- und Verspätungszeiten möglich. 

Für die Abschätzung einer geplanten Reise wäre es sehr hilfreich zu wissen, welche Verspätungen zu erwarten sind. Dies einmal mit Blick auf die letzten Tage; genauso spannend ist auch die Sicht auf den spezifischen Wochentag aus den letzten Kalenderwochen.

** Eingabemaske **
* Zugnummer
* Wochentag (Fahrtdatum)
* Startbahnhof (optional)
* Zielbahnhof

** Ausgabefenster **
(bitte keine Durchschnitte errechnen, da diese kaum aussagekräftig sind)
Tabelle - Letzte 10 Kalendertage
* "Bahnhof" .................... Startbahnhof ..... Zielbahnhof
* Kalendertag -1 ............ +/- Minuten ..... +/- Minuten
* Kalendertag -2 ............ +/- Minuten ..... +/- Minuten
* ...
* Kalendertag -10 .......... +/- Minuten ..... +/- Minuten
* .
* Kalenderwoche -1 ...... +/- Minuten ..... +/- Minuten
* Kalenderwoche -2 ...... +/- Minuten ..... +/- Minuten
* ...
* Kalenderwoche -10 .... +/- Minuten ..... +/- Minuten

**Comment by marudor** [comment]
Bewusst kein feature. Wird nicht kommen.
