### ISSUE TITLE
What do the ✈ symbols with the number next to them mean?

### ISSUE THREAD

**Issue by Ein-Tim** [marudor/bahn.expert#981]
Hi there! I have a question. There seems to be some sort of new feature or functionality that was implemented but not explained. When looking at some trains on bahn.expert, some stops have a ✈/✈️ symbol next to the name of the stop with a flightnumber look-a-like. What exactly is this and what information can I draw from this? Does it show me stops that have an airport in the same city/region? What is the number after the ✈ symbol?

For clarification, here's a screenshot:

<img width="1440" alt="Bildschirmfoto 2024-11-14 um 13 35 18" src="https://github.com/user-attachments/assets/b14c8eb4-7eb6-4bd4-93b0-39753aa1d0a0">

**Comment by marudor** [comment]
At those Stops or rather the part until the next Stop this Train also has a Lufthansa Flight number.
