### ISSUE TITLE
Zugnummernsuche: Filter für Verkehr im eigenen Land

### ISSUE THREAD

**Issue by b-pfl** [marudor/bahn.expert#984]
**Is your feature request related to a problem? Please describe.**
Die Zugnummernsuche ist per default so eingestellt, dass sämtliche Züge, die seitens der APIs geliefert werden, angezeigt werden. Das umfasst meist auch Züge / Busse im Ausland, die dort unter der gleichen (Teil-)Nummer laufen, womit es oft länger dauert, den richtigen Datensatz auszuwählen (was vor allem auf kleinen Telefonscreens Scrollen bedeuten kann). 

**Describe the solution you'd like**
Falls die Daten es hergeben, wäre es super, wenn man analog zur Wahl des Verkehrsmittels an Bahnhöfen (z.B. nur Fernverkehr, ...) auch bei der Zugnummernsuche ein oder mehrere Länder vorgeben kann, in denen die Suche exklusiv durchgeführt wird. Bsp für Deutschland: Wenn D ausgewählt wird, werden nur Züge bei der Zugsuche zurückgeliefert, die mindestens einen Halt haben, dessen IBNR mit 80... anfängt.

**Comment by marudor** [comment]
Lässt sich nicht simpel filtern
