### ISSUE TITLE
Falscher Zuglauf bei Datumswechsel

### ISSUE THREAD

**Issue by b-pfl** [marudor/bahn.expert#986]
**Describe the bug**
Wenn man sich einen Zuglauf anzeigen lässt und über die Pfeiltasten oben zu einem früheren oder späteren Datum springt, kann es passieren, dass der dann angezeigte Zuglauf nicht zum ursprünglich gewählten Zug passt - vermutlich betrifft das Züge im internationalen Kontext, wenn Zugnummern teils doppelt vergeben sind.

**To Reproduce**
1. Zuglauf für den EN346 (Berlin-Stockholm) wählen
2. Auf "<" klicken, um den Zuglauf vom Vortag anzeigen zu lassen
Angezeigt wird dann aber der Zuglauf vom NZ346 Bucarest-Wien statt vom EN346 Berlin-Stockholm

**Expected behavior**
Anzeige des "richtigen" Zuges

**Solution?**
Vermutlich hilft es, die Zuggattung mitzusenden?

**Comment by n-st** [comment]
Die Zuggattung wird in der URL anscheinend auch ignoriert: https://bahn.expert/details/ICE%20549/1732624684000 zeigt Informationen zum RJ 549 statt zum ICE 549.
(Unpraktisch — die URL wurde so von travelynx erzeugt; der Link "Zuglauf" in travelynx öffnet da also den Zuglauf für einen anderen Zug als den tatsächlich eingecheckten.)

**Comment by n-st** [comment]
Also, in https://github.com/marudor/bahn.expert/blob/main/src/server/rpc/journeys.ts#L201 sollte (laut dem verwendeten Regex und trim in https://github.com/marudor/bahn.expert/blob/main/src/server/journeys/journeyDetails.ts) noch korrekt die `category` "ICE" und `trainNumber` 549 ankommen.
Damit wird der hafasFallback übersprungen und die Verbindung an `findJourneyV1OrV2()` übergeben.

Dort greift für kürzliche Verbindungen `findJourneyV2()`; für ältere (> 4 Tage in der Vergangenheit) `findJourney()`.

Jetzt sieht es danach aus, dass `findJourneyV2()` die `category` ignoriert, daher eine Liste aller Züge mit passender Nummer zurückgibt — und daraus nimmt https://github.com/marudor/bahn.expert/blob/main/src/server/rpc/journeys.ts#L233 einfach das erste Ergebnis.

**Comment by marudor** [comment]
Fixed
