### ISSUE TITLE
Android App, Smaller Packages, Periodic Refresh

### ISSUE THREAD

**Issue by plutphil** [marudor/bahn.expert#987]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
I noticed that the JSON packages could be smaller when main data json is not inside a string inside another json. The format is also weird with this main list structure (helps maybe size reduction?)
I would like to have an android app, currently i try on working on it. :-)
**Describe alternatives you've considered**
A function to periodically refresh a station or train could be helpful but could also impact the server.
Flatten the json.
**Additional context**

**Comment by jheubuch** [comment]
You know, that publix API is not provided by @marudor?

As far as I know, the communication with the bahn.expert backend is handled via tRPC - so the structure of the JSON "packages" is in the corresponding tRPC protocol which both the server and the client can seamless understand and are type-safe with.
