### ISSUE TITLE
manchmal werden Züge nicht anhand ihres Namens gefunden, stattdessen andere angezeigt.

### ISSUE THREAD

**Issue by sh-dvl** [marudor/bahn.expert#989]
wird aus einer Bahnhofs-Liste der Abfahrten der Zug ausgewählt klappt das ganze, bei Direkteingabe schlägt es jedoch fehl.

Beispiel 2024-12-02 für ice 74:

richtiger zug: über Bhf Leipzig:
https://bahn.expert/details/ICE%2074/2024-12-02T08:59:00.000Z?evaNumberAlongRoute=8010205

ohne Parameter (aus Lesezeichen) zeigt es den RJ 74 zwischen Graz und Prag:
https://bahn.expert/details/ICE%2074/

wäre schick, wenn die exakte Eingabe eines Zugs auch zum exakten Ergebnis führen würde.

könnte evtl. mit #986 zusammenhängen.

**Comment by marudor** [comment]
Links sind immer nur mit Zeit eindeutig. Ich werds demnächst etwas verbessern. Aber einigermassen endeutig sind die URLs nur mit Zeiten.
Ist nicht 100% lösbar. (Ich schliess das hier, wie gesagt etwas verbessern kann ich es, steht eh auf meiner Liste)
